// const ERROR_INCORRECT_DATA = 400;
// const ERROR_AUTHORIZATION = 401;
// const ERROR_DELETE_CARD = 403;
// const ERROR_NOT_FOUND = 404;
// const ERROR_REGISTRATION = 409;
// const ERROR_DEFAULT = 500;
//
// module.exports = {
//   ERROR_INCORRECT_DATA,
//   ERROR_AUTHORIZATION,
//   ERROR_DELETE_CARD,
//   ERROR_NOT_FOUND,
//   ERROR_REGISTRATION,
//   ERROR_DEFAULT,
// };
